---
#clickhouse:
#  hosts:
#    clickhouse-01:
#      ansible_connection: docker
#vector:
#  hosts:
#    vector-01:
#      ansible_connection: docker
lighthouse:
  hosts:
    lighthouse-01:
      ansible_connection: ssh
      ansible_user: qqq
      ansible_host: 158.160.11.130