---

  - hosts: nodes
    become: yes
    become_user: root
    remote_user: vagrant

    tasks:

      - name: Installing tools
        apt: >
          package={{ item }}
          state=present
          update_cache=yes
        with_items:
          - git
          - curl

      - name: Installing docker
        shell: curl -fsSL get.docker.com -o get-docker.sh && chmod +x get-docker.sh && ./get-docker.sh

      - name: Add the current user to docker group
        user: name=vagrant append=yes groups=docker

      - name: Synchronization
        copy:
          src: stack/
          dest: "/opt/stack/"
          owner: root
          group: root
          mode: 0644
        become: true

#      - name: Folder init 1
#        file:
#          path: /opt/pg/vol_data
#          state: directory
#          owner: root
#          group: root
#          mode: 0775
#          recurse: yes
#
#      - name: Folder init 2
#        file:
#          path: /opt/pg/vol_bkup
#          state: directory
#          owner: root
#          group: root
#          mode: 0775
#          recurse: yes
#
#      - name: Folder init 3
#        file:
#          path: /opt/mysql/vol_data
#          state: directory
#          owner: root
#          group: root
#          mode: 0775
#          recurse: yes

      - name: Folder init 4
        file:
          path: /opt/elastic/data
          state: directory
          owner: root
          group: root
          mode: 0777
          recurse: yes

      - name: Folder init 5
        file:
          path: /opt/elastic/logs
          state: directory
          owner: root
          group: root
          mode: 0777
          recurse: yes

#      - name: Pull all images in compose
#        command: docker compose -f /opt/stack/docker-compose.yaml pull
#
#      - name: Up all services in compose
#        command: docker compose -f /opt/stack/docker-compose.yaml up -d