apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app.kubernetes.io/name: nginx-multitool
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-multitool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: registry.gitlab.com/madxboct/diplom-app/python-web:latest
        ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    app.kubernetes.io/name: nginx-multitool
  ports:
    - name: http-nginx-port
      protocol: TCP
      port: 9001
      targetPort: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: my-node-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-multitool
  ports:
    - name: node-tcp-nginx
      port: 9001
      targetPort: http-web-svc
      nodePort: 30007

#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: nginx-multitool-ingress
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Exact
#        backend:
#          service:
#            name: nginx-multitool-service
#            port:
#              number: 9001
#
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: example-service
#spec:
#  selector:
#    app.kubernetes.io/name: nginx-multitool
#  ports:
#    - port: 8765
#      targetPort: 9001
#  type: LoadBalancer
