kind: Namespace
apiVersion: v1
metadata:
  name: app
  labels:
    name: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: app
  labels:
    app.kubernetes.io/name: hello-world-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-app
    spec:
      containers:
      - name: nginx
        image: registry.gitlab.com/madxboct/diplom-app/python-web:latest
        ports:
        - containerPort: 80
          name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-svc-node
  namespace: app
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hello-world-app
  ports:
    - name: node-tcp-app
      port: 9001
      targetPort: http-web-svc
      nodePort: 30007
