---
- name: will wait till reachable
  hosts: all
  gather_facts: no # important
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        delay: 480
        timeout: 1200

    - name: Gather facts for the first time
      ansible.builtin.setup:

- name: Install k8s
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
  - k8s

- name: Configure k8s master
  hosts: k8s_masters
  remote_user: ubuntu
  become: yes

  roles:
  - k8s_master

- name: Configure k8s workers
  hosts: k8s_workers
  remote_user: ubuntu
  become: yes

  roles:
  - k8s_worker