---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
  - clickhouse

- name: Install vector
  hosts: vector
  roles:
  - vector-role

- name: Install lighthouse
  hosts: lighthouse
  roles:
  - lighthouse-role
